apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projects
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: Default project for ArgoCD
  destinations: # Allow deploying to any destination
    - namespace: '*'
      server: "*" # Allow deploying to any server
  sourceRepos:
    - '*' # Allow deploying from any repository

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'